CREATE TABLE IF NOT EXISTS kyc_submissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  nationality VARCHAR(100) NOT NULL,
  country_of_birth VARCHAR(100) NOT NULL,
  residential_address VARCHAR(255) NOT NULL,
  country_of_residence VARCHAR(100) NOT NULL,
  occupation VARCHAR(120) NOT NULL,
  employer VARCHAR(160) NULL,
  tax_residency VARCHAR(100) NOT NULL,
  tax_id VARCHAR(100) NULL,
  document_type ENUM('passport','national_id','drivers_license','residence_permit') NOT NULL,
  document_number VARCHAR(120) NOT NULL,
  issuing_country VARCHAR(100) NOT NULL,
  document_expiry DATE NOT NULL,
  account_purpose VARCHAR(255) NOT NULL,
  expected_monthly_volume VARCHAR(60) NOT NULL,
  source_of_funds VARCHAR(120) NOT NULL,
  is_pep BOOLEAN NOT NULL DEFAULT FALSE,
  is_beneficial_owner BOOLEAN NOT NULL DEFAULT TRUE,
  status ENUM('submitted','under_review','approved','rejected') NOT NULL DEFAULT 'submitted',
  rejection_reason VARCHAR(500) NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY kyc_user_unique (user_id),
  KEY kyc_status_index (status, submitted_at),
  CONSTRAINT kyc_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT kyc_reviewer_fk FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS kyc_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  submission_id BIGINT UNSIGNED NOT NULL,
  kind ENUM('identity_front','identity_back','proof_of_address','selfie') NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  storage_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(80) NOT NULL,
  size_bytes INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY kyc_document_kind_unique (submission_id, kind),
  CONSTRAINT kyc_document_submission_fk FOREIGN KEY (submission_id) REFERENCES kyc_submissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;