"use client";
import {FormEvent,useEffect,useState} from "react";
import {Bot,MessageCircle,Send,UserRound} from "lucide-react";
type Conversation={id:number;first_name:string;last_name:string;email:string;unread_count:number;last_message:string};type Message={id:number;sender_role:"user"|"admin"|"bot";message:string;created_at:string};
export default function AdminLiveChat(){
  const[items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function loadList(){const r=await fetch("/api/admin/support-chat",{cache:"no-store"}),d=await r.json();if(r.ok)setItems(d.conversations||[])}
  async function loadMessages(userId:number){const r=await fetch(`/api/admin/support-chat?userId=${userId}`,{cache:"no-store"}),d=await r.json();if(r.ok)setMessages(d.messages||[])}
  useEffect(()=>{loadList();const timer=setInterval(()=>{loadList();if(selected)loadMessages(selected.id)},5000);return()=>clearInterval(timer)},[selected]);
  async function send(e:FormEvent){e.preventDefault();if(!selected)return;const r=await fetch("/api/admin/support-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:selected.id,message})}),d=await r.json();if(!r.ok)return setError(d.error);setMessage("");await loadMessages(selected.id);await loadList()}
  return <section className="mt-10"><div className="flex items-center gap-3"><MessageCircle className="text-bank-700"/><div><h2 className="text-2xl font-bold">Live customer chat</h2><p className="text-xs text-neutral-500">Customer, automated bot, and administrator messages are clearly identified.</p></div></div><div className="card mt-5 grid min-h-[480px] overflow-hidden rounded-2xl md:grid-cols-[300px_1fr]"><aside className="border-r bg-neutral-50">{items.length?items.map(item=><button key={item.id} onClick={()=>{setSelected(item);loadMessages(item.id)}} className={`block w-full border-b p-4 text-left ${selected?.id===item.id?"bg-bank-50":"hover:bg-white"}`}><div className="flex justify-between gap-2"><b className="text-sm">{item.first_name} {item.last_name}</b>{Number(item.unread_count)>0&&<span className="rounded-full bg-red-500 px-2 py-0.5 text-[9px] font-bold text-white">{item.unread_count}</span>}</div><p className="mt-1 truncate text-[10px] text-neutral-500">{item.email}</p><p className="mt-2 truncate text-xs text-neutral-500">{item.last_message}</p></button>):<p className="p-8 text-center text-sm text-neutral-400">No chat conversations yet.</p>}</aside><div className="flex min-h-[480px] flex-col">{selected?<><div className="border-b p-4"><b>{selected.first_name} {selected.last_name}</b><p className="text-xs text-neutral-500">{selected.email}</p></div><div className="flex-1 space-y-4 overflow-y-auto p-5">{messages.map(item=>{const admin=item.sender_role==="admin",bot=item.sender_role==="bot";return <div key={item.id} className={`max-w-[85%] rounded-2xl border p-3 text-sm ${admin?"ml-auto border-bank-700 bg-bank-700 text-white":bot?"border-amber-200 bg-amber-50 text-amber-950":"border-gold-100 bg-gold-50 text-[#0a1728]"}`}><p className={`mb-1 flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-widest ${admin?"text-gold-300":bot?"text-amber-700":"text-gold-700"}`}>{bot?<Bot size={12}/>:<UserRound size={12}/>} {admin?"Customer care":bot?"SecurePath Bank Bot":"Customer"}</p><p className="whitespace-pre-wrap break-words">{item.message}</p><p className="mt-1 text-[9px] opacity-60">{new Date(item.created_at).toLocaleString("en-GB")}</p></div>})}</div><form onSubmit={send} className="flex gap-2 border-t p-4"><input required maxLength={2000} className="field" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Reply as customer care..."/><button className="btn px-4"><Send size={16}/></button></form>{error&&<p className="px-4 pb-3 text-xs text-red-700">{error}</p>}</>:<div className="grid flex-1 place-items-center text-sm text-neutral-400">Select a customer conversation.</div>}</div></div></section>
}

// Hostinger source snapshot sync.
