"use client";
import Image from "next/image";
import { FormEvent,useEffect,useState } from "react";
import { ImageUp,Save,Trash2 } from "lucide-react";
type Profile={firstName:string;lastName:string;email:string;phone:string;residentialAddress:string;country:string;preferredLanguage:string;transactionAlerts:boolean;marketingEmails:boolean;avatarUrl:string|null};
export default function AdminProfileSettings(){
  const[p,setP]=useState<Profile|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[avatarSaving,setAvatarSaving]=useState(false);
  useEffect(()=>{fetch("/api/banking/profile").then(async r=>{const d=await r.json();r.ok?setP(d.profile):setError(d.error)})},[]);
  async function submit(e:FormEvent){e.preventDefault();if(!p)return;setSaving(true);setError("");setMessage("");const r=await fetch("/api/banking/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}),d=await r.json();setSaving(false);if(!r.ok)return setError(d.error);setMessage("Administrator profile settings saved.")}
  async function upload(file?:File){if(!file||!p)return;setAvatarSaving(true);setError("");const form=new FormData();form.set("avatar",file);const r=await fetch("/api/banking/profile/avatar",{method:"POST",body:form}),d=await r.json();setAvatarSaving(false);if(!r.ok)return setError(d.error);setP({...p,avatarUrl:d.avatarUrl});setMessage("Profile picture updated. Refreshing the admin shell will display it.")}
  async function removeAvatar(){if(!p)return;setAvatarSaving(true);setError("");const r=await fetch("/api/banking/profile/avatar",{method:"DELETE"}),d=await r.json();setAvatarSaving(false);if(!r.ok)return setError(d.error);setP({...p,avatarUrl:null});setMessage("Profile picture removed.")}
  if(!p)return <div className="h-64 animate-pulse rounded-3xl bg-white"/>;
  const change=(patch:Partial<Profile>)=>setP({...p,...patch});
  return <section><p className="text-xs font-bold uppercase tracking-widest text-bank-600">Administrator account</p><h1 className="mt-2 text-4xl">Profile settings</h1><form onSubmit={submit} className="card mt-6 grid gap-5 rounded-3xl p-6 sm:grid-cols-2">
    <div className="flex flex-col gap-5 border-b pb-6 sm:col-span-2 sm:flex-row sm:items-center"><Image src={p.avatarUrl||"/images/securepathbank-profile-placeholder.webp"} alt="Administrator profile" width={96} height={96} className="size-24 rounded-full object-cover ring-4 ring-bank-50" unoptimized/><div className="flex-1"><b>{p.firstName} {p.lastName}</b><p className="mt-1 text-xs text-neutral-500">{p.email}</p><div className="mt-4 flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-bank-600 px-4 py-2.5 text-xs font-bold text-white"><ImageUp size={15}/>{avatarSaving?"Updating...":"Select picture"}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={avatarSaving} onChange={e=>upload(e.target.files?.[0])}/></label>{p.avatarUrl&&<button type="button" disabled={avatarSaving} onClick={removeAvatar} className="inline-flex items-center gap-2 rounded-md border border-red-200 px-4 py-2.5 text-xs font-bold text-red-700"><Trash2 size={15}/>Remove picture</button>}</div><p className="mt-2 text-[10px] text-neutral-400">JPEG, PNG or WebP, maximum 3 MB.</p></div></div>
    <Field label="First name" value={p.firstName} onChange={value=>change({firstName:value})}/><Field label="Last name" value={p.lastName} onChange={value=>change({lastName:value})}/><Field label="Phone" value={p.phone} onChange={value=>change({phone:value})}/><Field label="Country" value={p.country} onChange={value=>change({country:value})}/><label className="sm:col-span-2"><span className="label">Residential address</span><input className="field" value={p.residentialAddress} onChange={e=>change({residentialAddress:e.target.value})}/></label><label><span className="label">Preferred language</span><select className="field" value={p.preferredLanguage} onChange={e=>change({preferredLanguage:e.target.value})}><option value="en">English</option><option value="fr">French</option><option value="de">German</option><option value="es">Spanish</option></select></label><div className="space-y-3 pt-2"><label className="flex gap-2 text-sm"><input type="checkbox" checked={p.transactionAlerts} onChange={e=>change({transactionAlerts:e.target.checked})}/>Transaction alerts</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={p.marketingEmails} onChange={e=>change({marketingEmails:e.target.checked})}/>Marketing emails</label></div>{error&&<p className="text-sm text-red-700 sm:col-span-2">{error}</p>}{message&&<p className="text-sm text-gold-700 sm:col-span-2">{message}</p>}<button disabled={saving} className="btn sm:col-span-2"><Save size={16}/>{saving?"Saving...":"Save profile settings"}</button>
  </form></section>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label><span className="label">{label}</span><input required className="field" value={value||""} onChange={e=>onChange(e.target.value)}/></label>}

// Hostinger source snapshot sync.
