import mysql from 'mysql2/promise'
import {hash} from 'bcryptjs'
import {randomUUID} from 'node:crypto'
const base=process.env.APP_TEST_URL||'http://localhost:3000',password='SecureBankingTest!42',pin='4826',suffix=randomUUID(),senderEmail=`banking-sender-${suffix}@example.test`,recipientEmail=`banking-recipient-${suffix}@example.test`
const db=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD||'',database:process.env.DB_DATABASE})
async function session(email){const login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})}),challenge=login.headers.get('set-cookie')?.split(';')[0];if(!login.ok||!challenge)throw new Error('Banking smoke login failed.');const response=await fetch(`${base}/api/auth/pin`,{method:'POST',headers:{'content-type':'application/json',cookie:challenge},body:JSON.stringify({pin})}),header=response.headers.get('set-cookie')||'',cookie=header.split(',').map(x=>x.trim()).find(x=>x.startsWith('securepathbank_session='))?.split(';')[0];if(!response.ok||!cookie)throw new Error('Banking smoke PIN failed.');return cookie}
async function post(path,cookie,body){const response=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json',cookie},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(`${path}: ${data.error||response.status}`);return data}
async function cleanup(ids){if(!ids.length)return;const placeholders=ids.map(()=>'?').join(',');for(const table of ['transactions','crypto_swaps','crypto_deposit_credits','crypto_manual_credits','crypto_wallets','transfers','deposits','cards','support_tickets','grant_applications','accounts'])await db.query(`DELETE FROM ${table} WHERE user_id IN (${placeholders})`,ids);await db.query(`DELETE FROM users WHERE id IN (${placeholders})`,ids)}
const [stale]=await db.query("SELECT id FROM users WHERE email LIKE 'banking-sender-%@example.test' OR email LIKE 'banking-recipient-%@example.test'")
await cleanup(stale.map(user=>user.id))
try{const passwordHash=await hash(password,12),pinHash=await hash(pin,12);for(const [email,first] of [[senderEmail,'Sender'],[recipientEmail,'Recipient']])await db.execute("INSERT INTO users(email,password,password_hash,pin_hash,first_name,last_name,full_name,status,email_verified_at)VALUES(?,?,?,?,?,? ,?,'active',NOW())",[email,passwordHash,passwordHash,pinHash,first,'Test',`${first} Test`]);const [[sender]]=await db.query('SELECT id FROM users WHERE email=?',[senderEmail]),[[recipient]]=await db.query('SELECT id FROM users WHERE email=?',[recipientEmail]);await db.execute("INSERT INTO accounts(user_id,account_number,name,type,currency,ledger_balance,available_balance)VALUES(?,'7000000001','Checking Account','Checking Account','USD',1000,1000),(?,'7000000002','Checking Account','Checking Account','USD',0,0)",[sender.id,recipient.id]);const cookie=await session(senderEmail)
  const profileResponse=await fetch(`${base}/api/banking/profile`,{method:'PATCH',headers:{'content-type':'application/json',cookie},body:JSON.stringify({firstName:'Sender',lastName:'Test',phone:'+15555550101',residentialAddress:'1 Test Street',country:'United States',preferredLanguage:'en',transactionAlerts:true,marketingEmails:false})});if(!profileResponse.ok)throw new Error('Profile settings update failed.')
  const avatarForm=new FormData(),avatarBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');avatarForm.set('avatar',new Blob([avatarBytes],{type:'image/png'}),'avatar.png');const avatarResponse=await fetch(`${base}/api/banking/profile/avatar`,{method:'POST',headers:{cookie},body:avatarForm}),avatarData=await avatarResponse.json();if(!avatarResponse.ok||!avatarData.avatarUrl)throw new Error('Profile avatar upload failed.');const avatarDelete=await fetch(`${base}/api/banking/profile/avatar`,{method:'DELETE',headers:{cookie}});if(!avatarDelete.ok)throw new Error('Profile avatar removal failed.')
  const transfer=await post('/api/banking/transfers',cookie,{type:'internal',amount:125,recipientName:'Recipient Test',recipientAccount:'7000000002',bankName:'SecurePath Bank',pin});if(transfer.status!=='completed')throw new Error('Internal transfer did not complete.')
  await post('/api/banking/deposits',cookie,{method:'usdt'});await post('/api/banking/cards',cookie,{action:'apply',brand:'visa'});await post('/api/banking/requests',cookie,{type:'support',category:'account',subject:'Smoke test',message:'Automated test request',priority:'normal'});await post('/api/banking/requests',cookie,{type:'grant',applicantType:'individual',legalName:'Sender Test',projectTitle:'Smoke Test Community Project',category:'Community development',country:'United States',amount:500,timelineMonths:6,beneficiaries:10,purpose:'Automated grant workflow test with measurable community impact.',useOfFunds:'Testing materials, delivery, and reporting costs.'})
  const [balances]=await db.query('SELECT account_number,available_balance FROM accounts WHERE user_id IN (?,?) ORDER BY account_number',[sender.id,recipient.id]);if(Number(balances[0].available_balance)!==875||Number(balances[1].available_balance)!==125)throw new Error('Internal transfer balances are incorrect.')
  console.log('Banking smoke test passed.')
}finally{
  const [users]=await db.query('SELECT id FROM users WHERE email IN (?,?)',[senderEmail,recipientEmail]),ids=users.map(user=>user.id)
  await cleanup(ids)
  await db.end()
}
